kotlin2cpg: fix parsing of nop lambdas  (#1671)
* kotlin2cpg: fix parsing of nop lambdas

without this change, generating a CPG for a project containing a lambda
with no statements in its block crashes with a `NoSuchElementException`:
```
2022-08-10 11:44:33.325 INFO shutdown finished
java.util.NoSuchElementException: last of empty list
 at scala.collection.immutable.Nil$.last(List.scala:665)
 at scala.collection.immutable.Nil$.last(List.scala:661)
 at io.joern.kotlin2cpg.ast.KtPsiToAst.astsForBlock(KtPsiToAst.scala:411)
 at io.joern.kotlin2cpg.ast.KtPsiToAst.astsForBlock$(KtPsiToAst.scala:386)
 at io.joern.kotlin2cpg.passes.AstCreator.astsForBlock(AstCreator.scala:25)
 at io.joern.kotlin2cpg.ast.KtPsiToAst.$anonfun$astForLambda$4(KtPsiToAst.scala:530)

```

* Remove unused `vals`