trim querydb dependencies: fix testDistro.sh (#2757)
Querydb shipped a number of frontends in it's regular classpath, which
is causing problems with the usual suspects log4j/slf4j (see error below).
The main culprit is probably ghidra which ships an older version of log4j
in a fat jar.

```
Loading base CPG from:
/home/mp/Projects/shiftleft/joern/workspace/c/cpg.bin.tmp
java.lang.NoSuchMethodError: 'java.lang.ClassLoader[]
org.apache.logging.log4j.util.LoaderUtil.getClassLoaders()'
        at
org.apache.logging.log4j.core.impl.ThreadContextDataInjector.getServiceProviders(ThreadContextDataInjector.java:83)
        at
org.apache.logging.log4j.core.impl.ThreadContextDataInjector.initServiceProviders(ThreadContextDataInjector.java:73)
        at
org.apache.logging.log4j.core.impl.ThreadContextDataInjector.getProviders(ThreadContextDataInjector.java:285)
```